// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/falun/genny

package client

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/turbinelabs/api"
	httperr "github.com/turbinelabs/api/http/error"
	"github.com/turbinelabs/api/queryargs"
	"github.com/turbinelabs/api/service"
	tbnhttp "github.com/turbinelabs/client/http"
)

type httpDomainV1 struct {
	dest tbnhttp.Endpoint

	requestHandler tbnhttp.RequestHandler
}

// Construct a new HTTP backed Domain API implementation.
//
// Parameters:
//	dest - service handling our HTTP requests; cf. NewService
//	apiKey - key used to sign our API requests; cf. NewService
//	client - HTTP client used to make these requests; must NOT be nil
func NewDomainV1(
	dest tbnhttp.Endpoint,
	apiKey string,
	client *http.Client,
) (*httpDomainV1, error) {
	if client == nil {
		// Future investigation note: when nil is passed in here the actual failure
		// is way upstream in a curious way; investigating could lend understanding
		// of some cool go internals
		return nil, fmt.Errorf("Attempting to configure Domain with nil *http.Client")
	}
	return &httpDomainV1{dest, tbnhttp.NewRequestHandler(client, apiKey, apiClientID)}, nil
}

// creates a domain-scoped version of the specified path
func (hc *httpDomainV1) path(p string) string {
	return "/v1.0/domain" + p
}

// Construct a request to the associated domain Endpoint with a specified
// method, path, query params, and body.
func (hc *httpDomainV1) request(
	method httpMethod,
	path string,
	params tbnhttp.Params,
	body string,
) (*http.Request, error) {
	rdr := strings.NewReader(body)
	req, err := http.NewRequest(string(method), hc.dest.Url(hc.path(path), params), rdr)

	if err != nil {
		return nil, err
	}

	return req, nil
}

func (hc *httpDomainV1) get(path string, params tbnhttp.Params) (*http.Request, error) {
	return hc.request(mGET, path, params, "")
}

func (hc *httpDomainV1) post(
	path string,
	params tbnhttp.Params,
	body string,
) (*http.Request, error) {
	return hc.request(mPOST, path, params, body)
}

func (hc *httpDomainV1) put(
	path string,
	params tbnhttp.Params,
	body string,
) (*http.Request, error) {
	return hc.request(mPUT, path, params, body)
}

func (hc *httpDomainV1) delete(path string, params tbnhttp.Params) (*http.Request, error) {
	return hc.request(mDELETE, path, params, "")
}

func (hc *httpDomainV1) Index(filters ...service.DomainFilter) (api.Domains, error) {
	params := tbnhttp.Params{}

	if filters != nil && len(filters) != 0 {
		filterBytes, e := json.Marshal(filters)
		if e != nil {
			return nil, httperr.New400(
				fmt.Sprintf("unable to encode domain filters: %v", filters),
				httperr.UnknownUnclassifiedCode)
		}

		params[queryargs.IndexFilters] = string(filterBytes)
	}

	response := make(api.Domains, 0, 10)
	reqFn := func() (*http.Request, error) { return hc.get("", params) }

	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return nil, err
	}

	return response, nil
}

func (hc *httpDomainV1) Get(key api.DomainKey) (api.Domain, error) {
	reqFn := func() (*http.Request, error) {
		return hc.get("/"+url.QueryEscape(string(key)), nil)
	}

	response := api.Domain{}
	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return api.Domain{}, err
	}

	return response, nil
}

func mkEncodeDomainError(domain api.Domain) *httperr.Error {
	msg := fmt.Sprintf("could not encode provided domain: %+v", domain)
	return httperr.New400(msg, httperr.UnknownEncodingCode)
}

func (hc *httpDomainV1) Create(newDomain api.Domain) (api.Domain, error) {
	encoded := ""

	if b, err := json.Marshal(newDomain); err == nil {
		encoded = string(b)
	} else {
		return api.Domain{}, mkEncodeDomainError(newDomain)
	}

	reqFn := func() (*http.Request, error) { return hc.post("", nil, encoded) }
	response := api.Domain{}
	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return api.Domain{}, err
	}

	return response, nil
}

func (hc *httpDomainV1) Modify(domain api.Domain) (api.Domain, error) {
	encoded := ""

	if b, err := json.Marshal(domain); err == nil {
		encoded = string(b)
	} else {
		return api.Domain{}, mkEncodeDomainError(domain)
	}

	response := api.Domain{}
	reqFn := func() (*http.Request, error) {
		return hc.put("/"+url.QueryEscape(string(domain.DomainKey)), nil, encoded)
	}

	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return api.Domain{}, err
	}

	return response, nil
}

func (hc *httpDomainV1) Delete(
	domainKey api.DomainKey,
	checksum api.Checksum,
) error {
	reqFn := func() (*http.Request, error) {
		return hc.delete(
			"/"+url.QueryEscape(string(domainKey)),
			tbnhttp.Params{queryargs.Checksum: checksum.Checksum},
		)
	}

	if err := hc.requestHandler.Do(reqFn, nil); err != nil {
		return err
	}

	return nil
}

func (hc *httpDomainV1) Purge(_ api.DomainKey, _ api.Checksum) error {
	return httperr.New501("Purge not implemented", httperr.MiscErrorCode)
}
