// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/falun/genny

package client

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/turbinelabs/api"
	httperr "github.com/turbinelabs/api/http/error"
	"github.com/turbinelabs/api/queryargs"
	"github.com/turbinelabs/api/service"
	tbnhttp "github.com/turbinelabs/client/http"
)

type httpZoneV1 struct {
	dest tbnhttp.Endpoint

	requestHandler tbnhttp.RequestHandler
}

// Construct a new HTTP backed Zone API implementation.
//
// Parameters:
//	dest - service handling our HTTP requests; cf. NewService
//	apiKey - key used to sign our API requests; cf. NewService
//	client - HTTP client used to make these requests; must NOT be nil
func NewZoneV1(
	dest tbnhttp.Endpoint,
	apiKey string,
	client *http.Client,
) (*httpZoneV1, error) {
	if client == nil {
		// Future investigation note: when nil is passed in here the actual failure
		// is way upstream in a curious way; investigating could lend understanding
		// of some cool go internals
		return nil, fmt.Errorf("Attempting to configure Zone with nil *http.Client")
	}
	return &httpZoneV1{dest, tbnhttp.NewRequestHandler(client, apiKey, apiClientID)}, nil
}

// creates a zone-scoped version of the specified path
func (hc *httpZoneV1) path(p string) string {
	return "/v1.0/zone" + p
}

// Construct a request to the associated zone Endpoint with a specified
// method, path, query params, and body.
func (hc *httpZoneV1) request(
	method httpMethod,
	path string,
	params tbnhttp.Params,
	body string,
) (*http.Request, error) {
	rdr := strings.NewReader(body)
	req, err := http.NewRequest(string(method), hc.dest.Url(hc.path(path), params), rdr)

	if err != nil {
		return nil, err
	}

	return req, nil
}

func (hc *httpZoneV1) get(path string, params tbnhttp.Params) (*http.Request, error) {
	return hc.request(mGET, path, params, "")
}

func (hc *httpZoneV1) post(
	path string,
	params tbnhttp.Params,
	body string,
) (*http.Request, error) {
	return hc.request(mPOST, path, params, body)
}

func (hc *httpZoneV1) put(
	path string,
	params tbnhttp.Params,
	body string,
) (*http.Request, error) {
	return hc.request(mPUT, path, params, body)
}

func (hc *httpZoneV1) delete(path string, params tbnhttp.Params) (*http.Request, error) {
	return hc.request(mDELETE, path, params, "")
}

func (hc *httpZoneV1) Index(filters ...service.ZoneFilter) (api.Zones, error) {
	params := tbnhttp.Params{}

	if filters != nil && len(filters) != 0 {
		filterBytes, e := json.Marshal(filters)
		if e != nil {
			return nil, httperr.New400(
				fmt.Sprintf("unable to encode zone filters: %v", filters),
				httperr.UnknownUnclassifiedCode)
		}

		params[queryargs.IndexFilters] = string(filterBytes)
	}

	response := make(api.Zones, 0, 10)
	reqFn := func() (*http.Request, error) { return hc.get("", params) }

	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return nil, err
	}

	return response, nil
}

func (hc *httpZoneV1) Get(key api.ZoneKey) (api.Zone, error) {
	reqFn := func() (*http.Request, error) {
		return hc.get("/"+url.QueryEscape(string(key)), nil)
	}

	response := api.Zone{}
	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return api.Zone{}, err
	}

	return response, nil
}

func mkEncodeZoneError(zone api.Zone) *httperr.Error {
	msg := fmt.Sprintf("could not encode provided zone: %+v", zone)
	return httperr.New400(msg, httperr.UnknownEncodingCode)
}

func (hc *httpZoneV1) Create(newZone api.Zone) (api.Zone, error) {
	encoded := ""

	if b, err := json.Marshal(newZone); err == nil {
		encoded = string(b)
	} else {
		return api.Zone{}, mkEncodeZoneError(newZone)
	}

	reqFn := func() (*http.Request, error) { return hc.post("", nil, encoded) }
	response := api.Zone{}
	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return api.Zone{}, err
	}

	return response, nil
}

func (hc *httpZoneV1) Modify(zone api.Zone) (api.Zone, error) {
	encoded := ""

	if b, err := json.Marshal(zone); err == nil {
		encoded = string(b)
	} else {
		return api.Zone{}, mkEncodeZoneError(zone)
	}

	response := api.Zone{}
	reqFn := func() (*http.Request, error) {
		return hc.put("/"+url.QueryEscape(string(zone.ZoneKey)), nil, encoded)
	}

	if err := hc.requestHandler.Do(reqFn, &response); err != nil {
		return api.Zone{}, err
	}

	return response, nil
}

func (hc *httpZoneV1) Delete(
	zoneKey api.ZoneKey,
	checksum api.Checksum,
) error {
	reqFn := func() (*http.Request, error) {
		return hc.delete(
			"/"+url.QueryEscape(string(zoneKey)),
			tbnhttp.Params{queryargs.Checksum: checksum.Checksum},
		)
	}

	if err := hc.requestHandler.Do(reqFn, nil); err != nil {
		return err
	}

	return nil
}

func (hc *httpZoneV1) Purge(_ api.ZoneKey, _ api.Checksum) error {
	return httperr.New501("Purge not implemented", httperr.MiscErrorCode)
}
