// Code generated by MockGen. DO NOT EDIT.
// Source: stats.go

// Package client is a generated GoMock package.
package client

import (
	gomock "github.com/golang/mock/gomock"
	stats "github.com/turbinelabs/api/service/stats"
	executor "github.com/turbinelabs/nonstdlib/executor"
	reflect "reflect"
)

// mockInternalStatsClient is a mock of internalStatsClient interface
type mockInternalStatsClient struct {
	ctrl     *gomock.Controller
	recorder *mockInternalStatsClientMockRecorder
}

// mockInternalStatsClientMockRecorder is the mock recorder for mockInternalStatsClient
type mockInternalStatsClientMockRecorder struct {
	mock *mockInternalStatsClient
}

// newMockInternalStatsClient creates a new mock instance
func newMockInternalStatsClient(ctrl *gomock.Controller) *mockInternalStatsClient {
	mock := &mockInternalStatsClient{ctrl: ctrl}
	mock.recorder = &mockInternalStatsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *mockInternalStatsClient) EXPECT() *mockInternalStatsClientMockRecorder {
	return m.recorder
}

// ForwardV2 mocks base method
func (m *mockInternalStatsClient) ForwardV2(arg0 *stats.PayloadV2) (*stats.ForwardResult, error) {
	ret := m.ctrl.Call(m, "ForwardV2", arg0)
	ret0, _ := ret[0].(*stats.ForwardResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForwardV2 indicates an expected call of ForwardV2
func (mr *mockInternalStatsClientMockRecorder) ForwardV2(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardV2", reflect.TypeOf((*mockInternalStatsClient)(nil).ForwardV2), arg0)
}

// Query mocks base method
func (m *mockInternalStatsClient) Query(arg0 *stats.Query) (*stats.QueryResult, error) {
	ret := m.ctrl.Call(m, "Query", arg0)
	ret0, _ := ret[0].(*stats.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query
func (mr *mockInternalStatsClientMockRecorder) Query(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*mockInternalStatsClient)(nil).Query), arg0)
}

// Close mocks base method
func (m *mockInternalStatsClient) Close() error {
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *mockInternalStatsClientMockRecorder) Close() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*mockInternalStatsClient)(nil).Close))
}

// ForwardWithCallback mocks base method
func (m *mockInternalStatsClient) ForwardWithCallback(arg0 *stats.PayloadV2, arg1 executor.CallbackFunc) error {
	ret := m.ctrl.Call(m, "ForwardWithCallback", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForwardWithCallback indicates an expected call of ForwardWithCallback
func (mr *mockInternalStatsClientMockRecorder) ForwardWithCallback(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForwardWithCallback", reflect.TypeOf((*mockInternalStatsClient)(nil).ForwardWithCallback), arg0, arg1)
}
