// Automatically generated by MockGen. DO NOT EDIT!
// Source: stats.go

package client

import (
	gomock "github.com/golang/mock/gomock"
	stats "github.com/turbinelabs/api/service/stats"
	executor "github.com/turbinelabs/nonstdlib/executor"
)

// Mock of internalStatsClient interface
type mockInternalStatsClient struct {
	ctrl     *gomock.Controller
	recorder *_MockInternalStatsClientRecorder
}

// Recorder for mockInternalStatsClient (not exported)
type _MockInternalStatsClientRecorder struct {
	mock *mockInternalStatsClient
}

func newMockInternalStatsClient(ctrl *gomock.Controller) *mockInternalStatsClient {
	mock := &mockInternalStatsClient{ctrl: ctrl}
	mock.recorder = &_MockInternalStatsClientRecorder{mock}
	return mock
}

func (_m *mockInternalStatsClient) EXPECT() *_MockInternalStatsClientRecorder {
	return _m.recorder
}

func (_m *mockInternalStatsClient) Forward(_param0 *stats.Payload) (*stats.ForwardResult, error) {
	ret := _m.ctrl.Call(_m, "Forward", _param0)
	ret0, _ := ret[0].(*stats.ForwardResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockInternalStatsClientRecorder) Forward(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Forward", arg0)
}

func (_m *mockInternalStatsClient) Query(_param0 *stats.Query) (*stats.QueryResult, error) {
	ret := _m.ctrl.Call(_m, "Query", _param0)
	ret0, _ := ret[0].(*stats.QueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockInternalStatsClientRecorder) Query(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Query", arg0)
}

func (_m *mockInternalStatsClient) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockInternalStatsClientRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}

func (_m *mockInternalStatsClient) ForwardWithCallback(_param0 *stats.Payload, _param1 executor.CallbackFunc) error {
	ret := _m.ctrl.Call(_m, "ForwardWithCallback", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockInternalStatsClientRecorder) ForwardWithCallback(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ForwardWithCallback", arg0, arg1)
}
