// Code generated by MockGen. DO NOT EDIT.
// Source: api_key.go

// Package flags is a generated GoMock package.
package flags

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAPIAuthKeyFromFlags is a mock of APIAuthKeyFromFlags interface
type MockAPIAuthKeyFromFlags struct {
	ctrl     *gomock.Controller
	recorder *MockAPIAuthKeyFromFlagsMockRecorder
}

// MockAPIAuthKeyFromFlagsMockRecorder is the mock recorder for MockAPIAuthKeyFromFlags
type MockAPIAuthKeyFromFlagsMockRecorder struct {
	mock *MockAPIAuthKeyFromFlags
}

// NewMockAPIAuthKeyFromFlags creates a new mock instance
func NewMockAPIAuthKeyFromFlags(ctrl *gomock.Controller) *MockAPIAuthKeyFromFlags {
	mock := &MockAPIAuthKeyFromFlags{ctrl: ctrl}
	mock.recorder = &MockAPIAuthKeyFromFlagsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAPIAuthKeyFromFlags) EXPECT() *MockAPIAuthKeyFromFlagsMockRecorder {
	return m.recorder
}

// Make mocks base method
func (m *MockAPIAuthKeyFromFlags) Make() string {
	ret := m.ctrl.Call(m, "Make")
	ret0, _ := ret[0].(string)
	return ret0
}

// Make indicates an expected call of Make
func (mr *MockAPIAuthKeyFromFlagsMockRecorder) Make() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockAPIAuthKeyFromFlags)(nil).Make))
}
