// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package flags is a generated GoMock package.
package flags

import (
	gomock "github.com/golang/mock/gomock"
	service "github.com/turbinelabs/api/service"
	reflect "reflect"
)

// MockClientFromFlags is a mock of ClientFromFlags interface
type MockClientFromFlags struct {
	ctrl     *gomock.Controller
	recorder *MockClientFromFlagsMockRecorder
}

// MockClientFromFlagsMockRecorder is the mock recorder for MockClientFromFlags
type MockClientFromFlagsMockRecorder struct {
	mock *MockClientFromFlags
}

// NewMockClientFromFlags creates a new mock instance
func NewMockClientFromFlags(ctrl *gomock.Controller) *MockClientFromFlags {
	mock := &MockClientFromFlags{ctrl: ctrl}
	mock.recorder = &MockClientFromFlagsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientFromFlags) EXPECT() *MockClientFromFlagsMockRecorder {
	return m.recorder
}

// Validate mocks base method
func (m *MockClientFromFlags) Validate() error {
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate
func (mr *MockClientFromFlagsMockRecorder) Validate() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockClientFromFlags)(nil).Validate))
}

// Make mocks base method
func (m *MockClientFromFlags) Make() (service.All, error) {
	ret := m.ctrl.Call(m, "Make")
	ret0, _ := ret[0].(service.All)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make
func (mr *MockClientFromFlagsMockRecorder) Make() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockClientFromFlags)(nil).Make))
}

// MakeAdmin mocks base method
func (m *MockClientFromFlags) MakeAdmin() (service.Admin, error) {
	ret := m.ctrl.Call(m, "MakeAdmin")
	ret0, _ := ret[0].(service.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeAdmin indicates an expected call of MakeAdmin
func (mr *MockClientFromFlagsMockRecorder) MakeAdmin() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeAdmin", reflect.TypeOf((*MockClientFromFlags)(nil).MakeAdmin))
}
