/*
Copyright 2017 Turbine Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Automatically generated by MockGen. DO NOT EDIT!
// Source: api_key.go

package flags

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of APIAuthKeyFromFlags interface
type MockAPIAuthKeyFromFlags struct {
	ctrl     *gomock.Controller
	recorder *_MockAPIAuthKeyFromFlagsRecorder
}

// Recorder for MockAPIAuthKeyFromFlags (not exported)
type _MockAPIAuthKeyFromFlagsRecorder struct {
	mock *MockAPIAuthKeyFromFlags
}

func NewMockAPIAuthKeyFromFlags(ctrl *gomock.Controller) *MockAPIAuthKeyFromFlags {
	mock := &MockAPIAuthKeyFromFlags{ctrl: ctrl}
	mock.recorder = &_MockAPIAuthKeyFromFlagsRecorder{mock}
	return mock
}

func (_m *MockAPIAuthKeyFromFlags) EXPECT() *_MockAPIAuthKeyFromFlagsRecorder {
	return _m.recorder
}

func (_m *MockAPIAuthKeyFromFlags) Make() string {
	ret := _m.ctrl.Call(_m, "Make")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockAPIAuthKeyFromFlagsRecorder) Make() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Make")
}
